version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  webshell:
    build: ./tty/
    privileged: true
    hostname: webshell
    expose: 
      - "7681"
    environment:
      - VIRTUAL_HOST=webshell.localhost
      - VIRTUAL_PORT=7681
      - SSH_PORT=22

  ubuntu-0:
    build: ./ubuntu-ssh/
    hostname: 'foo.bar'
    expose:
      - "22"
  ubuntu-1:
    build: ./ubuntu-ssh/
    hostname: 'foo.bar'
    expose:
      - "22"
  ubuntu-3:
    build: ./ubuntu-ssh/
    hostname: 'foo.bar'
    expose:
      - "22"
  ubuntu-4:
    build: ./ubuntu-ssh/
    hostname: 'foo.bar'
    expose:
      - "22"
  ubuntu-5:
    build: ./ubuntu-ssh/
    hostname: 'foo.bar'
    expose:
      - "22"
  ubuntu-6:
    build: ./ubuntu-ssh/
    hostname: 'foo.bar'
    expose:
      - "22"